version: '3.8'
services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: api_students
      MYSQL_ROOT_PASSWORD: root

    ports:
      - '3305:3306'
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - bridge
    restart: always
  app:
    build: ./docker_tp
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: api_students
    ports:
      - '9000:9000'
    depends_on:
      - db
    restart: always
    networks:
      - bridge

volumes : 
  data: 
networks:
  bridge:

